FROM alpine:latest

LABEL maintainer.0="xanimo (@xanimo)"

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV DOGECOIN_DATA=/home/dogecoin/.dogecoin
ENV DOGECOIN_PREFIX=/opt/dogecoin-1.14.4-dev
ENV PATH=${DOGECOIN_PREFIX}/bin:$PATH

# Hotfix for glibc hack that fixes the order of DNS resolving (i.e. check /etc/hosts first and then lookup DNS-servers).
# To fix this we just create /etc/nsswitch.conf and add the following line:
RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

RUN sed -i 's/http\:\/\/dl-cdn.alpinelinux.org/https\:\/\/alpine.global.ssl.fastly.net/g' /etc/apk/repositories \
  && adduser -S dogecoin \
  && set -x \
  && apk add --no-cache \
  boost-filesystem \
  boost-system \
  boost-thread \
  libevent \
  libzmq \
  su-exec \
  alpine-sdk \
  && echo "en_US.UTF-8 UTF-8" > /etc/profile.d/locale.sh

COPY dogecoin.conf /home/dogecoin/.dogecoin/dogecoin.conf
COPY torrc.default /etc/tor/torrc.default
RUN chown -R dogecoin /etc/tor
COPY dogecoind /opt/dogecoin-1.14.4-dev/bin/dogecoind
COPY dogecoin-cli /opt/dogecoin-1.14.4-dev/bin/dogecoin-cli
COPY dogecoin-tx /opt/dogecoin-1.14.4-dev/bin/dogecoin-tx
COPY libdogecoinconsensus.a /opt/dogecoin-1.14.4-dev/libdogecoinconsensus.a
COPY libdogecoinconsensus.so /opt/dogecoin-1.14.4-dev/libdogecoinconsensus.so
COPY libdogecoinconsensus.so.0.0.0 /opt/dogecoin-1.14.4-dev/libdogecoinconsensus.so.0.0.0

COPY docker-entrypoint.sh /entrypoint.sh

RUN ["chmod", "+x", "/entrypoint.sh"]

VOLUME ["/home/dogecoin/.dogecoin"]

EXPOSE 22555 22556 44555 44556 18444 9050 9051

ENTRYPOINT ["/entrypoint.sh"]

RUN dogecoind -version | grep "Dogecoin Core Daemon version v${DOGECOIN_VERSION}"

CMD ["dogecoind"]
