on:
  push:
    branches: [ 1.14.6-dev ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file 1.14.6-dev/Dockerfile --tag xanimo/1.14.6-dev:$(date +%s)